### ISSUE TITLE
truly_minimal branch: jupyter-server instead of notebook?

### ISSUE THREAD

**Issue by consideRatio** [binder-examples/minimal-dockerfile#3]
There is a `truly-minimal` branch, which currently install the `notebook` package. Would it be even more minimal to install `jupyter-server`?

I built the following Dockerfile with the repo2docker's current master, but got an error related to starting `jupyter-notebook`.

```Dockerfile
FROM python:3.8-slim
RUN pip install --no-cache jupyter-server
ENV HOME=/tmp
```

```
$ repo2docker .
Successfully built 1d4528cf542d
Successfully tagged r2d-2e1604580226:latest
Traceback (most recent call last):
  File "/usr/local/bin/jupyter", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/jupyter_core/command.py", line 247, in main
    command = _jupyter_abspath(subcommand)
  File "/usr/local/lib/python3.8/site-packages/jupyter_core/command.py", line 133, in _jupyter_abspath
    raise Exception(
Exception: Jupyter command `jupyter-notebook` not found.
```

I tried the following, which did work though.

```
$ repo2docker . jupyter-server --allow-root
[I 2020-11-05 12:48:24.922 ServerApp] Writing notebook server cookie secret to /tmp/.local/share/jupyter/runtime/jupytr_cookie_secret
[I 2020-11-05 12:48:24.940 ServerApp] Serving notebooks from local directory: /
[I 2020-11-05 12:48:24.940 ServerApp] Jupyter Server 1.0.5 is running at:
[I 2020-11-05 12:48:24.940 ServerApp] http://localhost:8888/?token=e46775c0465420dbf34b93cc0e28c4a363d60bc577bc1088
[I 2020-11-05 12:48:24.940 ServerApp]  or http://127.0.0.1:8888/?token=e46775c0465420dbf34b93cc0e28c4a363d60bc577bc1088
[I 2020-11-05 12:48:24.940 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2020-11-05 12:48:24.943 ServerApp] 
    
    To access the server, open this file in a browser:
        file:///tmp/.local/share/jupyter/runtime/jpserver-1-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=e46775c0465420dbf34b93cc0e28c4a363d60bc577bc1088
     or http://127.0.0.1:8888/?token=e46775c0465420dbf34b93cc0e28c4a363d60bc577bc1088
```

But, could a repo about to be build override this command, I'm not sure. Does binderhub support alternative entrypoints?

**Comment by yuvipanda** [comment]
You could use alternate entrypoints with `start`. However, IIRC if you just install jupyter-server, it comes with no interfaces - just an API endpoint. Would that be useful?

**Comment by consideRatio** [comment]
Ah thank you @yuvipanda for nudging me in the right direction!

I looked to create a lightning fast image to build so binderhub CI system could save time, this was accomplished in another way by using a Dockerfile with a single FROM step using another image already built minimally like this, so this is now a question of curiosity for me only to do this with jupyter-server.

The result is in https://github.com/bunderhub-ci-repos/minimal-dockerfile and the cached-minimal-dockerfile repo. I have an open binderhub PR to use these as well which cut CI test duration in ~half.
